-- MySQL Script generated by MySQL Workbench
-- Thu Nov  1 17:52:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inter` ;
USE `inter` ;

-- -----------------------------------------------------
-- Table `inter`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombrerol` VARCHAR(45) NULL,
  `activorol` TINYINT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NULL,
  `sapellido` VARCHAR(45) NULL,
  `ci` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `activo` TINYINT NULL,
  `rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_persona_rol1_idx` (`rol_id_rol` ASC),
  CONSTRAINT `fk_persona_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `activousuario` TINYINT NULL,
  `fechacreacion` DATETIME NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `persona_id_persona`),
  INDEX `fk_usuario_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`funcionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`funcionalidad` (
  `id_funcionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombrefuncionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`privilegios` (
  `rol_id_rol` INT NOT NULL,
  `funcionalidad_id_funcionalidad` INT NOT NULL,
  INDEX `fk_privilegios_rol1_idx` (`rol_id_rol` ASC),
  INDEX `fk_privilegios_funcionalidad1_idx` (`funcionalidad_id_funcionalidad` ASC),
  CONSTRAINT `fk_privilegios_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privilegios_funcionalidad1`
    FOREIGN KEY (`funcionalidad_id_funcionalidad`)
    REFERENCES `inter`.`funcionalidad` (`id_funcionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`cuenta` (
  `rol_id_rol` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  INDEX `fk_cuenta_rol_idx` (`rol_id_rol` ASC),
  INDEX `fk_cuenta_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_cuenta_rol`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `inter`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `activoestudiante` TINYINT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `persona_id_persona`),
  INDEX `fk_estudiante_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombrecarrera` VARCHAR(45) NULL,
  `modalidad` VARCHAR(45) NULL,
  `version` INT NULL,
  `activocarrera` TINYINT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`estudia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`estudia` (
  `estudiante_id_estudiante` INT NOT NULL,
  `estudiante_persona_id_persona` INT NOT NULL,
  `carrera_id_carrera` INT NOT NULL,
  INDEX `fk_estudia_estudiante1_idx` (`estudiante_id_estudiante` ASC, `estudiante_persona_id_persona` ASC),
  INDEX `fk_estudia_carrera1_idx` (`carrera_id_carrera` ASC),
  CONSTRAINT `fk_estudia_estudiante1`
    FOREIGN KEY (`estudiante_id_estudiante` , `estudiante_persona_id_persona`)
    REFERENCES `inter`.`estudiante` (`id_estudiante` , `persona_id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudia_carrera1`
    FOREIGN KEY (`carrera_id_carrera`)
    REFERENCES `inter`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `activoempleado` TINYINT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `persona_id_persona`),
  INDEX `fk_empleado_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`representante` (
  `id_representante` INT NOT NULL AUTO_INCREMENT,
  `activorep` TINYINT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_representante`, `persona_id_persona`),
  INDEX `fk_representante_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_representante_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombreempresa` VARCHAR(45) NULL,
  `direccionempresa` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `activoempresa` TINYINT NULL,
  `representante_id_representante` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_empresa_representante1_idx` (`representante_id_representante` ASC),
  CONSTRAINT `fk_empresa_representante1`
    FOREIGN KEY (`representante_id_representante`)
    REFERENCES `inter`.`representante` (`id_representante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`pasantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`pasantia` (
  `id_pasantia` INT NOT NULL AUTO_INCREMENT,
  `numpasantia` INT NULL,
  `fechainicio` DATE NULL,
  `fechafin` DATE NULL,
  `gestion` YEAR NULL,
  `anexo` VARCHAR(100) NULL,
  `estadopasantia` INT NULL,
  `activopasantia` TINYINT NULL,
  `empleado_id_empleado` INT NOT NULL,
  `empleado_persona_id_persona` INT NOT NULL,
  `empresa_id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_pasantia`),
  INDEX `fk_pasantia_empleado1_idx` (`empleado_id_empleado` ASC, `empleado_persona_id_persona` ASC),
  INDEX `fk_pasantia_empresa1_idx` (`empresa_id_empresa` ASC),
  CONSTRAINT `fk_pasantia_empleado1`
    FOREIGN KEY (`empleado_id_empleado` , `empleado_persona_id_persona`)
    REFERENCES `inter`.`empleado` (`id_empleado` , `persona_id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasantia_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `inter`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombreasignatura` VARCHAR(45) NULL,
  `nivel` INT NULL,
  `descripcionasig` VARCHAR(500) NULL,
  `activoasignatura` TINYINT NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`tiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`tiene` (
  `pasantia_id_pasantia` INT NOT NULL,
  `asignatura_id_asignatura` INT NOT NULL,
  INDEX `fk_tiene_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  INDEX `fk_tiene_asignatura1_idx` (`asignatura_id_asignatura` ASC),
  CONSTRAINT `fk_tiene_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tiene_asignatura1`
    FOREIGN KEY (`asignatura_id_asignatura`)
    REFERENCES `inter`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `notasupervisor` FLOAT NULL,
  `notatutor` FLOAT NULL,
  `notafinal` FLOAT NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_nota_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_nota_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`visita` (
  `id_visita` INT NOT NULL AUTO_INCREMENT,
  `fechavisita` DATE NULL,
  `observaciones` VARCHAR(500) NULL,
  `anexovisita` VARCHAR(100) NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  PRIMARY KEY (`id_visita`),
  INDEX `fk_visita_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_visita_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`documentacion` (
  `id_documentacion` INT NOT NULL AUTO_INCREMENT,
  `nombredoc` VARCHAR(100) NULL,
  `fechaentrega` DATE NULL,
  `respaldo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_documentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`entrega` (
  `documentacion_id_documentacion` INT NOT NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  INDEX `fk_entrega_documentacion1_idx` (`documentacion_id_documentacion` ASC),
  INDEX `fk_entrega_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_entrega_documentacion1`
    FOREIGN KEY (`documentacion_id_documentacion`)
    REFERENCES `inter`.`documentacion` (`id_documentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`cuadernillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`cuadernillo` (
  `id_cuadernillo` INT NOT NULL AUTO_INCREMENT,
  `numerosemana` INT NULL,
  `fechainicio` DATE NULL,
  `fechafin` DATE NULL,
  `lunes` VARCHAR(1000) NULL,
  `martes` VARCHAR(1000) NULL,
  `miercoles` VARCHAR(1000) NULL,
  `jueves` VARCHAR(1000) NULL,
  `viernes` VARCHAR(1000) NULL,
  `sabado` VARCHAR(1000) NULL,
  `domingo` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_cuadernillo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`pasanillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`pasanillo` (
  `cuadernillo_id_cuadernillo` INT NOT NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  INDEX `fk_pasanillo_cuadernillo1_idx` (`cuadernillo_id_cuadernillo` ASC),
  INDEX `fk_pasanillo_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_pasanillo_cuadernillo1`
    FOREIGN KEY (`cuadernillo_id_cuadernillo`)
    REFERENCES `inter`.`cuadernillo` (`id_cuadernillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasanillo_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT  INTO `funcionalidad`(`id_funcionalidad`,`nombrefuncionalidad`) VALUES 
(1,'crear/editar'),
(2,'visualizar'),
(3,'todo');

INSERT  INTO `rol`(`id_rol`,`nombrerol`,`activorol`) VALUES 
(1,'administrador',1),
(2,'personal',1),
(3,'estudiante',1);

INSERT  INTO `privilegios`(`rol_id_rol`,`funcionalidad_id_funcionalidad`) VALUES 
(2,1),
(3,2),
(1,3);

INSERT  INTO `persona`(`id_persona`,`nombre`,`papellido`,`sapellido`,`ci`,`telefono`,`direccion`,`email`,`rol_id_rol`,`activo`) VALUES 
(1,'admin','admin','admin','admin',0,'admin','admin@admin.com',1,1);

INSERT  INTO `usuario`(`id_usuario`,`usuario`,`clave`,`persona_id_persona`,`activousuario`,`fechacreacion`) VALUES 
(1,'admin@admin.com','21232f297a57a5a743894a0e4a801fc3',1,1,'2018-09-11 12:47:59');

INSERT  INTO `cuenta`(`usuario_id_usuario`,`usuario_persona_id_persona`,`rol_id_rol`) VALUES 
(1,1,1);
INSERT INTO `empleado` (`persona_id_persona`, `cargo`, `activoempleado`) VALUES ('1', 'administrador', '1');